export const QUERY_PARAMS_TYPE = 'QUERY_PARAMS';

export const SIDEBAR_LOAD_CHANGE = 'SIDEBAR/LOAD_CHANGE';
export const SIDEBAR_MODAL_CHANGE = 'SIDEBAR/MODAL_CHANGE';
export const SIDEBAR_SET_NEWS = 'SIDEBAR/SET_NEWS';

export const NEWSLIST_LOAD_CHANGE = 'NEWSLIST/LOAD_CHANGE';
export const NEWSLIST_MODAL_CHANGE = 'NEWSLIST/MODAL_CHANGE';
export const NEWSLIST_SET_NEWS = 'NEWSLIST/SET_NEWS';